Erol444/TravianBotSharp

- TravBotSharp/Views/VillageViews/FarmingNonGoldUc.cs
> resolve #5

- .github/workflows/dev.yml
- .github/workflows/main.yml
- TravBotSharp/FodyWeavers.xml
- TravBotSharp/Properties/app.manifest
- TravBotSharp/TbsWinForms.csproj
- TravBotSharp/packages.config
add Fody/Costura reduce amount file dll in folder
> add Fody/Costura

- TbsCore/Tasks/LowLevel/ChangeVillageName.cs
- TbsCore/TbsCore.csproj
- TbsCore/packages.lock.json
- TravBotSharp/TbsWinForms.csproj
- TravBotSharp/packages.config
in T4.5 they change how you change your village's name
this will fix it
> fix change name village task

- TbsCore/Tasks/LowLevel/UpgradeBuilding.cs
- TbsCore/TbsCore.csproj
- TbsCore/packages.lock.json
- TravBotSharp/Properties/AssemblyInfo.cs
- TravBotSharp/TbsWinForms.csproj
- TravBotSharp/packages.config
Found by Merlin#7649
Work only for Travian company's ads
Need more contributions from others since my server only shows travian's ads =))
> Skip video ads

- TbsCore/Core/WebBrowserInfo.cs
- TbsCore/Helpers/HttpHelper.cs
- TbsCore/Helpers/InactiveFinder/InactiveSearchIt.cs
- TbsCore/Helpers/InactiveFinder/TravianStatsDe.cs
- TbsCore/Helpers/ProxyHelper.cs
- TravBotSharp/Forms/AddAccount.cs
- TravBotSharp/Forms/InactiveFinder.Designer.cs
- TravBotSharp/Forms/InactiveFinder.cs
just code without test
needs acc in the server which is on inactivesearch.it but not in travianstats.de
> add inactivesearch.it to farm finder

- TravBotSharp/Views/VillageViews/FarmingNonGoldUc.Designer.cs
- TravBotSharp/Views/VillageViews/FarmingNonGoldUc.cs
- TravBotSharp/packages.config
add a button to delete farmlist 
add more delay in every time it sends (from EriK)
add limited 15 farms per list to the official Travian server
add "USE AT YOUR OWN RISK" since this function makes bot's activities look like bot =))
> Update non gold farmlist

- TravBotSharp/Views/VillageViews/FarmingNonGoldUc.Designer.cs
- TravBotSharp/Views/VillageViews/FarmingNonGoldUc.cs
> i forgot commit these

- TbsCore/Core/PostLoadHelper.cs
- TbsCore/Core/TaskExecutor.cs
- TbsCore/Helpers/BuildingHelper.cs
- TbsCore/Models/VillageModels/VillBuilding.cs
- TbsCore/Tasks/LowLevel/SendSettlers.cs
- TbsCore/Tasks/LowLevel/TrainSettlers.cs
- TbsCore/Tasks/LowLevel/UpgradeBuilding.cs
- TravBotSharp/Views/VillageViews/BuildUc.Designer.cs
- TravBotSharp/Views/VillageViews/BuildUc.cs
some quick improvements. tested it on ttwars and bot constantly makes new villas every ~10min, which is great:)
> Improvements

- .github/workflows/release.yml
- TbsCore/Core/WebBrowserInfo.cs
yes, this fixes not responding when chrome browser closes (manually or crash)
sorry because typo on branch name
> Fix not responding when chrome close

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
So from now, pre-release and release will create by merging branch
If PR has label "pre-release", it will run pre-release workflow
If PR has label "release", it will run release workflow
If PR has no label, it just merges without any run
make sure u don't have any commit straight to master and develop branch, it will broke this system ( I think ._. )
> More ci cd

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
sorry =)) it seem like the one I test in my fork i didn't paste to this repo
> fix workflow

- .github/workflows/pre-release.yml
seem like i forgot change pre-release workflow
> fix pre-release workflow

- .github/workflows/release.yml
- TbsCore/Helpers/AccountHelper.cs
- TbsCore/Models/Settings/GeneralSettings.cs
- TravBotSharp/ControlPanel.Designer.cs
- TravBotSharp/ControlPanel.cs
- TravBotSharp/Views/DebugUc.cs
- TravBotSharp/Views/GeneralUc.Designer.cs
- TravBotSharp/Views/GeneralUc.cs
Fix error in the latest release 
sorry because didn't test it carefully
> Hotfix 1.300.0

- .github/workflows/pre-release.yml
- TbsCore/Helpers/UpdateAccountObject.cs
- TbsCore/Helpers/VillageHelper.cs
- TbsCore/Parsers/RightBarParser.cs
- TbsCore/TbsCore.csproj
- TbsCore/packages.lock.json
- TravBotSharp/TbsWinForms.csproj
- TravBotSharp/Views/GeneralUc.Designer.cs
- TravBotSharp/packages.config
Because of  [Polarbear 1233.1 Updates](https://blog.travian.com/2021/08/changelog-release-polarbear-1233-1/), they change how villages list shows
> Fix village list reader

- .github/workflows/build.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- README.md
- TbsCore/Models/Access/Access.cs
- TbsCore/Models/Access/AccessInfo.cs
- TbsCore/TbsCore.csproj
- TbsCore/packages.lock.json
- TravBotSharp/TbsWinForms.csproj
- TravBotSharp/packages.config
> Fix ci cd (#59)

- TbsCore/Helpers/TroopsHelper.cs
- TbsCore/Tasks/SecondLevel/SendReinforcementScouts.cs
- TbsCore/TravianData/TroopsData.cs
- TravBotSharp/TbsWinForms.csproj
- TravBotSharp/UserControls/TroopSelector.Designer.cs
- TravBotSharp/UserControls/TroopSelector.cs
- TravBotSharp/UserControls/TroopSelector.resx
- TravBotSharp/Views/VillageViews/TroopsUc.Designer.cs
- TravBotSharp/Views/VillageViews/TroopsUc.cs
Also added function to manually add  a troop to ToImprove village list
> Send scouts to all villages

- TbsCore/Core/TaskExecutor.cs
- TbsCore/Helpers/BuildingHelper.cs
- TbsCore/Models/VillageModels/BuildingCurrently.cs
- TbsCore/Parsers/InfrastructureParser.cs
- TbsCore/Tasks/LowLevel/UpgradeBuilding.cs
not sure how to update location though
> Fix currently building update

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- TbsCore/Core/TaskTimer.cs
- TbsCore/Core/WebBrowserInfo.cs
- TbsCore/Helpers/AccountHelper.cs
- TbsCore/Helpers/IoHelperCore.cs
- TbsCore/Helpers/TimeHelper.cs
- TbsCore/Models/Logging/LogOutput.cs
- TbsCore/Models/Logging/SerilogSingleton.cs
- TbsCore/Models/Logging/Sink.cs
- TbsCore/Tasks/LowLevel/ChangeAccess.cs
- TbsCore/Tasks/LowLevel/ReopenDriver.cs
- TbsCore/Tasks/LowLevel/Sleep.cs
- TravBotSharp/ControlPanel.cs
- TravBotSharp/Views/GeneralUc.cs
- Add more technical tricks to Tbs's browser
- Change where bot saves data ( now bot save data in the same folder has executable file)
- Change how bot upgrades building ( it now continue to build until fulfilling the village's building queue before doing another task )
- Fix bug bot upgrade more than 1 lv building
- Cure Tbs's Alzheimer's disease
- Change how bot sleep, change proxy, ...
- Remove inactive farm finder ( will reappear next pre-release ( or 2 ) )
> Hot fix weekly 26 03 2022

- TbsCore/Tasks/LowLevel/UpgradeBuilding.cs
- Update chrome driver v98 to v100
- Teach Tbs how to deal with exhausted resources and missing prerequisite
- Tell TBS don't crash while watching debug tab
- Redesign side region ( move all buttons to top)
- Add Add account (has s in its text) to add bulk accounts instead of one by one ( Request by Luda Fizz)
- Teach TBS how to switch villages in the TTWars server
- Teach TBS the right way to enter the building (the main reason TBS cannot send farm list correctly)
- Teach TBS how to close itself without showing an error
- Teach TBS how to pause correctly
- Teach TBS how to deal when no proxies are available
- Redesign Hero tab 
- Add auto auction (Request by MU)
- Tell TBS switch village when upgrade building queue empty is not a good ideal
- TBS now has a loading screen when startup & …
> Weekly 02 04 2022 - Re-merged because workflow fail

- TbsCore/Models/Logging/LogOutput.cs
- TbsCore/Tasks/LowLevel/HeroEquip.cs
- TbsCore/Tasks/LowLevel/SellOnAuctions.cs
- TbsCore/Tasks/LowLevel/UpgradeBuilding.cs
- TravBotSharp/ControlPanel.cs
- Teach TBS again how to use hero resource ( now it won't loop infinitely)
- TBS no longer watches an ad when upgrading a building  (Official Travian) (I'm not sure but it cause a lot of exception since chrome v100)  
- Tell TBS slow down when selling items on auction.
- Tell TBS logout button is clickable 
- Tell TBS to calm down when lack of resource
> Hotfix 06 04 2022

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- TbsCore/Database/DbRepository.cs
- TbsCore/Helpers/IoHelperCore.cs
- TbsCore/Helpers/NavigationHelper.cs
- TbsCore/Tasks/LowLevel/ReviveHero.cs
- TbsCore/Tasks/LowLevel/UpgradeBuilding.cs
- TravBotSharp/Forms/AddAccounts.cs
- TravBotSharp/Forms/Hero/UpdateSettings.Designer.cs
- TravBotSharp/Forms/Hero/UpdateSettings.cs
- Tell TBS that Travian devs change id of build button
- Teach TBS that the TTWars server has a different tab id for the construction page
- Tell TBS using Javascript in hero revive task is not a good idea 
- TBS learned that Add accounts should import account show on check textbox
> Hotfix 15 04 2022

- .github/workflows/build.yml
- TbsCore/Helpers/AccountHelper.cs
- TbsCore/Helpers/DriverHelper.cs
- TbsCore/Helpers/NavigationHelper.cs
- TbsCore/Parsers/ResourceParser.cs
- TbsCore/Tasks/LowLevel/UpgradeBuilding.cs
- Complete research about changing id from Offical Travian and TTWars
- TBS now can read cost upgrade on TTWars better than before
- Tell TBS it is a good idea if it waits for a moment before clicking while executing upgrade building task
- TBS will more detail what it has done in the log while executing upgrade building task
> Fix 16 04 2022

- TbsCore/Core/TaskExecutor.cs
- TbsCore/Core/WebBrowserInfo.cs
- TbsCore/Helpers/DriverHelper.cs
- TbsCore/Helpers/NavigationHelper.cs
- TbsCore/Helpers/UpgradeBuildingHelper.cs
- TbsCore/Helpers/VillageHelper.cs
- TbsCore/Tasks/LowLevel/BotTask.cs
- TbsCore/Tasks/LowLevel/HeroEquip.cs
- TbsCore/Tasks/LowLevel/LoginTask.cs
- TbsCore/Tasks/LowLevel/TrainSettlers.cs
- TbsCore/Tasks/LowLevel/UpgradeBuilding.cs
- Train settlers now can train 3 instead of 1like before
- Update use hero res on train settlers
- Fix TBS doesn't know where is wall
- Fix TBS doesn't know user change favorite tab
> Fix 19 04 2022

- TbsCore/Tasks/LowLevel/UpgradeBuilding.cs
> Fix 22 04 2022

- TbsCore/Helpers/ResourcesHelper.cs
- TbsCore/Tasks/LowLevel/HeroEquip.cs
- TbsCore/Tasks/LowLevel/TrainSettlers.cs
- TbsCore/Tasks/LowLevel/UpgradeBuilding.cs
- fix bot click play button but that is autoplay ads cause bot pause ads ( why on earth did they add this? )
- fix train settler cannot find settler box in ttwars
- fix bot forget storage building is upgrading and keep adding storage upgrade when "storage is too low"
- fix hero use resources like human
> Fix 23 04 2022

- TbsCore/Core/TaskExecutor.cs
- TbsCore/Tasks/LowLevel/GetServerInfo.cs
- TbsCore/Tasks/LowLevel/LoginTask.cs
- TravBotSharp/Forms/AddAccount.cs
- TravBotSharp/Forms/AddAccounts.cs
**This version use chrome v101, make sure you update your chrome**
- Fix bot cannot log in after Travian release 1508.1 version, EU region will be updated at 29.04 ~10:03 UTC+1
> Fix 28 04 2022

- TbsCore/Helpers/Classificator.cs
- TbsCore/Tasks/Sim/ClaimBeginnerTask2021.cs
- TbsCore/Tasks/Update/CheckAttacks.cs
- TbsCore/Tasks/Update/UpdateTroops.cs
- TbsCore/Tasks/Update/UpdateVillage.cs
- Fix bot cannot collect all beginner quest 
- Fix bot cannot update new village 
> Fix 30 04 2022

- TbsCore/Core/PostLoadHelper.cs
- TbsCore/Core/TaskExecutor.cs
- TbsCore/Tasks/Sim/ClaimBeginnerTask2021.cs
- Tell bot that update hero info when user not allow is not a good idea
> 17 05 2022

- TbsCore/Core/PostLoadHelper.cs
- TbsCore/Core/WebBrowserInfo.cs
- TbsCore/Helpers/DriverHelper.cs
- TbsCore/Helpers/NavigationHelper.cs
- TbsCore/Helpers/VillageHelper.cs
- TbsCore/Tasks/Sim/ClaimBeginnerTask.cs
- TbsCore/Tasks/Sim/TrainSettlers.cs
- TbsCore/Tasks/Sim/UpgradeBuilding.cs
- Fix ttwars auto-upgrade resource field
- Fix ttwars claim beginner quests
- Fix ttwars switch village stuck
- Fix ttwars train settler
> Fix 19 05 2022

- TbsCore/Tasks/Update/GetServerInfo.cs
- fix TBS cannot read server speed and map size (Travian Offical)
> fix 20 05 2022

- TbsCore/Core/TaskTimer.cs
- TbsCore/Helpers/TimeHelper.cs
- TbsCore/Tasks/Browser/ReopenDriver.cs
- TravBotSharp/ControlPanel.cs
- TravBotSharp/TbsWinForms.csproj
- TravBotSharp/Views/VillageViews/BuildUc.Designer.cs
- TravBotSharp/Views/VillageViews/BuildUc.cs
**This version use chrome v102, make sure you update your chrome first**
- Update chromedriver to v102
- Fix bot cannot close if there is sleep account
> Fix 27 05 2022

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- Fix Settting hero UI (min max options)
- Add auto-update chromedriver
- Remove Defending & Discord tab
- Change from .Net Framework to .Net 6 (UI only, core library still using .Net Standard)
- Fix bot crash if using the old release (I just found out this recently, this is main reason why old TBS cannot be opened)
> Fix 13 06 2022

- TbsWinformNet6/Forms/Splash.cs
- Fix Settting hero UI (min max options)
- Add auto-update chromedriver
- Remove Defending & Discord tab
- Change from .Net Framework to .Net 6 (UI only, core library still using .Net Standard)
- Fix bot crash if using the old release (I just found out this recently, this is main reason why old TBS cannot be opened)
> Hotfix 13-06-2022

- TbsCore/Tasks/Update/HeroUpdateInfo.cs
**This version only works with Official Travian has new Hero UI**
- Fix bot forget reading info about hero's inventory
- Fix bot upgrade building one by one instead of 2 or 3 buildings one time ( plus + roman )
> Hotfix 16 06 2022

- MainCore/Helper/ClickHelper.cs
- MainCore/MainCore.csproj
- MainCore/Tasks/Sim/StartAdventure.cs
- MainCore/Tasks/Update/UpdateAdventures.cs
- MainCore/Tasks/Update/UpdateInfo.cs
- TTWarsCore/FindElements/HeroPage.cs
- Ignore other hero's status, now TBS won't stop if hero has different than "home"
- Update adventures now only run if user turn on auto start adventures
- Fix cannot start adventures in TTWars
> Update hero info 

- MainCore/Tasks/Attack/StartFarmList.cs
- MainCore/Tasks/BotTask.cs
- MainCore/Tasks/Misc/LoginTask.cs
- MainCore/Tasks/Misc/RefreshVillage.cs
- MainCore/Tasks/Update/UpdateAdventures.cs
- MainCore/Tasks/Update/UpdateBothDorf.cs
- MainCore/Tasks/Update/UpdateDorf1.cs
- MainCore/Tasks/Update/UpdateDorf2.cs
- MainCore/Tasks/Update/UpdateFarmList.cs
- MainCore/Tasks/Update/UpdateHeroItems.cs
- MainCore/Tasks/Update/UpdateInfo.cs
- MainCore/Tasks/Update/UpdateVillage.cs
- WPFUI/ViewModels/Tabs/Villages/SettingsViewModel.cs
- WPFUI/Views/Tabs/Villages/SettingsPage.xaml
- WPFUI/Views/Tabs/Villages/SettingsPage.xaml.cs
> Missing refresh village tickbox

- MainCore/Tasks/Misc/SleepTask.cs
> fix bot dont want to sleep more after first sleep

- MainCore/Tasks/Sim/UpgradeBuilding.cs
- MainCore/Tasks/Update/UpdateVillage.cs
> Instant upgrade problem with non-instant building

- MainCore/Tasks/Update/UpdateAdventures.cs
- MainCore/Tasks/Update/UpdateInfo.cs
> Fix send adventures fail

- MainCore/Helper/ClickHelper.cs
- MainCore/Helper/HeroHelper.cs
- MainCore/Helper/NavigateHelper.cs
- MainCore/MainCore.csproj
- MainCore/Tasks/Attack/StartFarmList.cs
- MainCore/Tasks/Misc/ImproveTroopsTask.cs
- MainCore/Tasks/Misc/LoginTask.cs
- MainCore/Tasks/Misc/NPCTask.cs
- MainCore/Tasks/Misc/RefreshVillage.cs
- MainCore/Tasks/Misc/SleepTask.cs
- MainCore/Tasks/Misc/UseHeroResources.cs
- MainCore/Tasks/Sim/InstantUpgrade.cs
- MainCore/Tasks/Sim/StartAdventure.cs
- MainCore/Tasks/Sim/UpgradeBuilding.cs
- MainCore/Tasks/Update/UpdateAdventures.cs
- MainCore/Tasks/Update/UpdateBothDorf.cs
- MainCore/Tasks/Update/UpdateDorf1.cs
- MainCore/Tasks/Update/UpdateDorf2.cs
- MainCore/Tasks/Update/UpdateFarmList.cs
- MainCore/Tasks/Update/UpdateHeroItems.cs
- MainCore/Tasks/Update/UpdateInfo.cs
- MainCore/Tasks/Update/UpdateTroopLevel.cs
- MainCore/Tasks/Update/UpdateVillage.cs
> Bot didnt check login page

- MainCore/Migrations/202210181120_UpgradeTroopMigrations.cs
> Bot crash with old database file

- MainCore/Helper/GithubHelper.cs
- WPFUI/ViewModels/VersionViewModel.cs
- WPFUI/Views/VersionWindow.xaml
- WPFUI/Views/VersionWindow.xaml.cs
> change version window ui

- MainCore/Tasks/Attack/StartFarmList.cs
> Fix send farmlist failed

- MainCore/MainCore.csproj
- MainCore/Tasks/Update/UpdateAdventures.cs
- TravianOfficialNewHeroUICore/Parsers/HeroInfo.cs
> Bot cannot send adventures

- .gitignore
- README.md
- WPFUI/Models/TroopInfo.cs
- WPFUI/ViewModels/Tabs/Villages/TroopsViewModel.cs
- WPFUI/ViewModels/Uc/CheckBoxWithInputViewModel.cs
- WPFUI/ViewModels/Uc/ResourcesViewModel.cs
- WPFUI/ViewModels/Uc/ResourcesWithStorageViewModel.cs
- WPFUI/ViewModels/Uc/ToleranceViewModel.cs
- WPFUI/Views/Uc/CheckBoxWithInputUc.xaml
- WPFUI/Views/Uc/CheckBoxWithInputUc.xaml.cs
- WPFUI/Views/Uc/FarmListControllerUc.xaml
- WPFUI/Views/Uc/FarmListControllerUc.xaml.cs
- WPFUI/Views/Uc/NormalBuildUc.xaml
- WPFUI/Views/Uc/ResBuildUc.xaml
- WPFUI/Views/Uc/ResourcesUc.xaml
- WPFUI/Views/Uc/ResourcesUc.xaml.cs
- WPFUI/Views/Uc/ResourcesWithStorageUc.xaml
- WPFUI/Views/Uc/ResourcesWithStorageUc.xaml.cs
- WPFUI/Views/Uc/ToleranceUc.xaml
- WPFUI/Views/Uc/ToleranceUc.xaml.cs
- WPFUI/Views/Uc/TroopsUc.xaml
- WPFUI/WPFUI.csproj
Using [Extended WPF Toolkit](https://github.com/xceedsoftware/wpftoolkit) for numeric input, no more textbox
> Add numeric input

- MainCore/Tasks/Misc/SleepTask.cs
- SLeep once and no second sleep
- Sleep cannot pause, now it can
> Sleep problem

- MainCore/AppDbContext.cs
- MainCore/Helper/UpgradeBuildingHelper.cs
- MainCore/Migrations/202210271504_NPCForWarhouse.cs
- MainCore/Migrations/2022102716038_IgnoreRomanAdvantage.cs
- MainCore/Models/Database/VillageSetting.cs
- MainCore/Tasks/Update/UpdateVillage.cs
- WPFUI/Models/VillageSetting.cs
- WPFUI/Views/Tabs/Villages/SettingsPage.xaml
- WPFUI/Views/Tabs/Villages/SettingsPage.xaml.cs
> Request from Kaii

- MainCore/Services/Implementations/TaskManager.cs
- MainCore/Tasks/Misc/NPCTask.cs
- MainCore/Tasks/Misc/RefreshVillage.cs
- MainCore/Tasks/Sim/UpgradeBuilding.cs
- MainCore/Tasks/Update/UpdateVillage.cs
- TravianOfficialCore/Parsers/HeroSectionParser.cs
- WPFUI/Models/VillageSetting.cs
- WPFUI/ViewModels/Tabs/Villages/InfoViewModel.cs
- WPFUI/ViewModels/Tabs/Villages/NPCViewModel.cs
- WPFUI/ViewModels/Uc/MainView/MainButtonPanelViewModel.cs
- WPFUI/Views/Tabs/Villages/SettingsPage.xaml.cs
- WPFUI/Views/Uc/MainView/MainButtonPanelUc.xaml.cs
- Move trigger auto task to refresh villlage task
- Fix npc failed
- Modify pause button's content
> Auto task trigger logic

- .github/workflows/build.yml
- .github/workflows/hotfix.yml
- .github/workflows/release.yml
- MainCore/Services/Implementations/TaskManager.cs
- MainCore/Tasks/Update/UpdateInfo.cs
- WPFUI/ViewModels/Uc/MainView/MainButtonPanelViewModel.cs
you can still use it when u compile bot in local
but be aware since they change UI, parsers are broken from now
> Remove TTWars from auto build

- MainCore/Errors/Skip.cs
- MainCore/Helper/Implementations/UpgradeBuildingHelper.cs
- MainCore/Services/Implementations/PlanManager.cs
- MainCore/Tasks/Misc/NPCTask.cs
- MainCore/Tasks/Sim/UpgradeBuilding.cs
- make code easier for reading
- fix upgrade building task crash when choosing building to build
> Optimize upgrade building

- MainCore/AppDbContext.cs
- MainCore/Migrations/202302101011_SleepWhenChangingProxy.cs
- MainCore/Models/Database/AccountSetting.cs
- MainCore/Tasks/Misc/SleepTask.cs
- MainCore/Tasks/Sim/UpgradeBuilding.cs
- WPFUI/Models/AccountSetting.cs
- WPFUI/ViewModels/Uc/MainView/MainButtonPanelViewModel.cs
- WPFUI/ViewModels/WaitingViewModel.cs
- WPFUI/Views/Tabs/SettingsPage.xaml
- WPFUI/Views/Tabs/SettingsPage.xaml.cs
- add force sleep setting (now when change proxy bot have to sleep based on setting instead of 15 mins, un tick will make bot sleep about 15mins between 2 proxy)
- optimize sleep task
> Optimize chrome activity

- MainCore/Services/Implementations/ChromeBrowser.cs
- MainCore/Services/Implementations/ChromeManager.cs
- WPFUI/Views/Tabs/SettingsPage.xaml
- WPFUI/Views/Tabs/SettingsPage.xaml.cs
- Fix bot cannot open 2 account in different server which have same proxy or default connection
> Chrome user data

- MainCore/Helper/Implementations/UpgradeBuildingHelper.cs
- Fix upgrade building roman keep looping if queue has only resource field
> Fix upgrade building roman keep looping

- MainCore/AppDbContext.cs
- MainCore/Errors/Skip.cs
- MainCore/Helper/Implementations/UpgradeBuildingHelper.cs
- MainCore/Migrations/202302101011_SleepWhenChangingProxy.cs
- MainCore/Models/Database/AccountSetting.cs
- MainCore/Services/Implementations/ChromeBrowser.cs
- MainCore/Services/Implementations/ChromeManager.cs
- MainCore/Services/Implementations/PlanManager.cs
- MainCore/Tasks/Misc/NPCTask.cs
- MainCore/Tasks/Misc/SleepTask.cs
- MainCore/Tasks/Sim/UpgradeBuilding.cs
- WPFUI/Models/AccountSetting.cs
- WPFUI/ViewModels/Uc/MainView/MainButtonPanelViewModel.cs
- WPFUI/ViewModels/WaitingViewModel.cs
- WPFUI/Views/Tabs/SettingsPage.xaml
- WPFUI/Views/Tabs/SettingsPage.xaml.cs
- fix upgrade building task crash when choosing the building to build
- add force sleep setting (now when changing proxy bot have to sleep based on the setting instead of 15 mins, untick will make the bot sleep about 15mins between 2 proxy)
- optimize sleep task
- fix bot don't know there is level 10 available to build resource bonus building (credit to Lasseroenn)
If you like my work, you can donate to me through [ko-fi.com/vinaghost](https://ko-fi.com/vinaghost)
> Release 2.6.0

- MainCore/Errors/Cancel.cs
- MainCore/Helper/Implementations/BuildingsHelper.cs
- MainCore/Helper/Implementations/UpgradeBuildingHelper.cs
- MainCore/Helper/Interface/IUpgradeBuildingHelper.cs
- MainCore/Services/Implementations/TaskManager.cs
- MainCore/Tasks/Attack/StartFarmList.cs
- MainCore/Tasks/Misc/ImproveTroopsTask.cs
- MainCore/Tasks/Misc/LoginTask.cs
- MainCore/Tasks/Misc/NPCTask.cs
- MainCore/Tasks/Misc/RefreshVillage.cs
- MainCore/Tasks/Misc/SleepTask.cs
- MainCore/Tasks/Misc/UseHeroResources.cs
- MainCore/Tasks/Sim/InstantUpgrade.cs
- MainCore/Tasks/Sim/StartAdventure.cs
- MainCore/Tasks/Sim/UpgradeBuilding.cs
- MainCore/Tasks/Update/UpdateAdventures.cs
- MainCore/Tasks/Update/UpdateBothDorf.cs
- MainCore/Tasks/Update/UpdateDorf1.cs
- MainCore/Tasks/Update/UpdateDorf2.cs
- MainCore/Tasks/Update/UpdateFarmList.cs
- MainCore/Tasks/Update/UpdateHeroItems.cs
- MainCore/Tasks/Update/UpdateInfo.cs
- MainCore/Tasks/Update/UpdateTroopLevel.cs
- MainCore/Tasks/Update/UpdateVillage.cs
- WPFUI/ViewModels/Uc/MainView/MainButtonPanelViewModel.cs
- WPFUI/Views/Tabs/DebugPage.xaml
- Change the column's width in debug tab for easy read
- Fix pause button not working (it is sleep button before :v )
- Change task flow of all task
> Optimize task flow

- WPFUI/ViewModels/Uc/MainView/MainButtonPanelViewModel.cs
> Add confirm dialogue to delete account

- MainCore/Helper/Implementations/Base/BuildingsHelper.cs
- MainCore/Helper/Interface/IBuildingsHelper.cs
- WPFUI/Store/AccountTabStore.cs
- WPFUI/ViewModels/Abstract/AccountTabBaseViewModel.cs
- WPFUI/ViewModels/Abstract/VillageTabBaseViewModel.cs
- WPFUI/ViewModels/MainWindowViewModel.cs
- WPFUI/ViewModels/Tabs/AddAccountViewModel.cs
- WPFUI/ViewModels/Tabs/AddAccountsViewModel.cs
- WPFUI/ViewModels/Tabs/EditAccountViewModel.cs
- WPFUI/ViewModels/Tabs/FarmingViewModel.cs
- WPFUI/ViewModels/Tabs/NoAccountViewModel.cs
- WPFUI/ViewModels/Tabs/SettingsViewModel.cs
- WPFUI/ViewModels/Tabs/Villages/BuildViewModel.cs
- WPFUI/ViewModels/Tabs/Villages/VillageSettingsViewModel.cs
- WPFUI/ViewModels/Uc/CheckBoxWithInputViewModel.cs
- WPFUI/ViewModels/Uc/MainLayoutViewModel.cs
- WPFUI/ViewModels/Uc/ResourcesViewModel.cs
- WPFUI/ViewModels/Uc/ResourcesWithStorageViewModel.cs
- WPFUI/ViewModels/Uc/ToleranceViewModel.cs
- WPFUI/ViewModels/Uc/TroopTrainingSelectorViewModel.cs
- WPFUI/ViewModels/Uc/VersionOverlayViewModel.cs
- WPFUI/ViewModels/Uc/WaitingOverlayViewModel.cs
- WPFUI/Views/Tabs/VillagesTab.xaml.cs
- WPFUI/Views/Uc/MainLayoutUc.xaml
- Fix UI crash
- Optimize UI loading
If you like my work, you can donate to me through [ko-fi.com/vinaghost](https://ko-fi.com/vinaghost)
> Hotfix 2.8.1

- MainCore/Helper/Implementations/Base/TrainTroopHelper.cs
- MainCore/Helper/Implementations/Base/UpgradeBuildingHelper.cs
- MainCore/Services/Implementations/PlanManager.cs
- MainCore/Services/Implementations/TaskManager.cs
- MainCore/Services/Interface/IPlanManager.cs
- MainCore/Tasks/FunctionTasks/TrainTroopsTask.cs
- Fix another crash bug
- Fix great stable train troop setting not works
- Add more info log to train troop task
If you like my work, you can donate to me through [ko-fi.com/vinaghost](https://ko-fi.com/vinaghost)
> Hotfix 2.8.2

- MainCore/Services/Implementations/ChromeBrowser.cs
- MainCore/Services/Implementations/ChromeDriverInstaller.cs
- MainCore/Services/Implementations/ChromeManager.cs
- MainCore/Services/Interface/IChromeManager.cs
- WPFUI/ViewModels/MainWindowViewModel.cs
Well Google Chrome dev team decide change how to match chrome browser with chrome driver
> Chrome driver update 

- MainCore/Services/Implementations/ChromeDriverInstaller.cs
- Fix bot stuck (null parameter)
If you like my work, you can donate to me through [ko-fi.com/vinaghost](https://ko-fi.com/vinaghost)
> Hotfix 2.9.1
